version: '3'
services:
    mysql:
        environment:
            MYSQL_ROOT_PASSWORD: "123456"
        image: "docker.io/mysql:5.7" 
        container_name: mysql
        restart: always
        volumes:
            - "./data/mysql:/var/lib/mysql"
        ports:
            - "3306:3306"
    redis:
      image: redis:latest
      container_name: redis
      command: redis-server --appendonly yes --requirepass "123456"
      ports:
        - "6379:6379"
      volumes:
        - "./data/redis:/data"
