// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1--rc1
// source: heart.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HeartServiceClient is the client API for HeartService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HeartServiceClient interface {
	GetUnaryHeart(ctx context.Context, in *HeartRequest, opts ...grpc.CallOption) (*HeartResponse, error)
}

type heartServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHeartServiceClient(cc grpc.ClientConnInterface) HeartServiceClient {
	return &heartServiceClient{cc}
}

func (c *heartServiceClient) GetUnaryHeart(ctx context.Context, in *HeartRequest, opts ...grpc.CallOption) (*HeartResponse, error) {
	out := new(HeartResponse)
	err := c.cc.Invoke(ctx, "/HeartService/GetUnaryHeart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HeartServiceServer is the server API for HeartService service.
// All implementations must embed UnimplementedHeartServiceServer
// for forward compatibility
type HeartServiceServer interface {
	GetUnaryHeart(context.Context, *HeartRequest) (*HeartResponse, error)
	mustEmbedUnimplementedHeartServiceServer()
}

// UnimplementedHeartServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHeartServiceServer struct {
}

func (UnimplementedHeartServiceServer) GetUnaryHeart(context.Context, *HeartRequest) (*HeartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUnaryHeart not implemented")
}
func (UnimplementedHeartServiceServer) mustEmbedUnimplementedHeartServiceServer() {}

// UnsafeHeartServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HeartServiceServer will
// result in compilation errors.
type UnsafeHeartServiceServer interface {
	mustEmbedUnimplementedHeartServiceServer()
}

func RegisterHeartServiceServer(s grpc.ServiceRegistrar, srv HeartServiceServer) {
	s.RegisterService(&HeartService_ServiceDesc, srv)
}

func _HeartService_GetUnaryHeart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeartServiceServer).GetUnaryHeart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HeartService/GetUnaryHeart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeartServiceServer).GetUnaryHeart(ctx, req.(*HeartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HeartService_ServiceDesc is the grpc.ServiceDesc for HeartService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HeartService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "HeartService",
	HandlerType: (*HeartServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUnaryHeart",
			Handler:    _HeartService_GetUnaryHeart_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "heart.proto",
}
