#!/bin/bash
#protoc --go_out=../cmd/protos --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative echo.proto --go-grpc_out=../cmd/protos
protoc --go_out=../cmd/protos --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative heart.proto --go-grpc_out=../cmd/protos
go mod tidy
